spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/version_2
    username: root
    password: 31102005

#    url: jdbc:postgresql://aws-1-ap-southeast-1.pooler.supabase.com:6543/postgres?prepareThreshold=0
#    username: postgres.vrtckvdzbjlpjexfacqm
#    password: 31102005
    driver-class-name: org.postgresql.Driver

  data:
    redis:
      host: localhost
      port: 6379

  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    show-sql: true
    open-in-view: true              # ✅ Tắt open-in-view để tránh giữ connection lâu

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  jackson:
    time-zone: Asia/Ho_Chi_Minh

logging:
  level:
    org.springframework.security: DEBUG
    com.zaxxer.hikari: INFO          # ✅ Thêm log để xem trạng thái pool

jwt:
  base64-secret: TKeq+EY8YJvX3hDTlt6Wor8TxGyYDYSs5Nieew3VAzL0G9XQcNFFJNOmIv2isY2ol8F9d29wnbdD7azzM0oqFQ==
  access-token-validity-in-seconds: 86400
  refresh-token-validity-in-seconds: 8640000

password:
  time_password_change_days: 30

cache:
  ttl:
    one-day-seconds: 86400       # 1 ngày
    one-week-seconds: 604800     # 1 tuần
    one-month-seconds: 2592000   # 30 ngày
