spring:
  datasource:
    #    url: jdbc:postgresql://localhost:5432/version_2
    #    username: root
    #    password: 31102005

    url: jdbc:postgresql://aws-1-ap-southeast-1.pooler.supabase.com:6543/postgres?sslmode=require&prepareThreshold=0&preparedStatementCacheQueries=0
    username: postgres.vrtckvdzbjlpjexfacqm
    password: 31102005
    driver-class-name: org.postgresql.Driver


    hikari:
      maximum-pool-size: 5           # ✅ Giới hạn tối đa 5 connection (đủ cho backend)
      minimum-idle: 1                # Giảm idle connection
      idle-timeout: 10000            # Đóng connection sau 10s không hoạt động
      max-lifetime: 300000           # Đổi connection sau 5 phút (phòng leak)
      connection-timeout: 10000      # Thời gian chờ nếu pool đầy
      leak-detection-threshold: 20000  # Log cảnh báo nếu connection mở >20s
      data-source-properties:
        cachePrepStmts: false
        prepStmtCacheSize: 0
        useServerPrepStmts: false
        prepareThreshold: 0
        preparedStatementCacheQueries: 0

  jpa:
    hibernate:
      ddl-auto: validate
    database: postgresql
    show-sql: true
    open-in-view: false              # ✅ Tắt open-in-view để tránh giữ connection lâu
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          batch_size: 20
        connection:
          provider_disables_autocommit: true
        temp:
          use_jdbc_metadata_defaults: false
        boot:
          allow_jdbc_metadata_access: false

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  jackson:
    time-zone: Asia/Ho_Chi_Minh

logging:
  level:
    org.springframework.security: DEBUG
    com.zaxxer.hikari: INFO          # ✅ Thêm log để xem trạng thái pool

jwt:
  base64-secret: TKeq+EY8YJvX3hDTlt6Wor8TxGyYDYSs5Nieew3VAzL0G9XQcNFFJNOmIv2isY2ol8F9d29wnbdD7azzM0oqFQ==
  access-token-validity-in-seconds: 86400
  refresh-token-validity-in-seconds: 8640000

password:
  time_password_change_days: 30
