spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/version_2}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:31102005}

    driver-class-name: org.postgresql.Driver

    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 300000
      max-lifetime: 1800000
      connection-timeout: 30000
      leak-detection-threshold: 60000
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST}
      port: ${SPRING_DATA_REDIS_PORT}
      username: ${SPRING_DATA_REDIS_USERNAME}
      password: ${SPRING_DATA_REDIS_PASSWORD}

      ssl:
        enabled: false

      repositories:
        enabled: true

  jpa:
    hibernate:
      ddl-auto: validate
    database: postgresql
    show-sql: false
    open-in-view: false
    repositories:
      enabled: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: UTC

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  jackson:
    time-zone: Asia/Ho_Chi_Minh

logging:
  level:
    org.springframework.data.repository.config.RepositoryConfigurationExtensionSupport: ERROR
    org.springframework.security: WARN
    com.zaxxer.hikari: WARN
    org.hibernate: WARN
    root: INFO

jwt:
  base64-secret: ${JWT_BASE64_SECRET}
  access-token-validity-in-seconds: ${JWT_ACCESS_TOKEN_VALIDITY_IN_SECONDS}
  refresh-token-validity-in-seconds: ${JWT_REFRESH_TOKEN_VALIDITY_IN_SECONDS}

password:
  time_password_change_days: ${TIME_PASSWORD_CHANGE_DAYS}

cache:
  ttl:
    one-day-seconds: 86400
    one-week-seconds: 604800
    one-month-seconds: 2592000

bytescale:
  account-id: ${BYTESCALE_ACCOUNT_ID}
  api-key: ${BYTESCALE_API_KEY}

server:
  port: ${PORT:${SERVER_PORT:8080}}
