spring:
  application:
    name: backend_version_2
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/version_2}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:password}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:update}
    database: ${JPA_DATABASE:postgresql}
    show-sql: ${JPA_SHOW_SQL:true}

  servlet:
    multipart:
      max-file-size: ${MULTIPART_MAX_FILE_SIZE:10MB}
      max-request-size: ${MULTIPART_MAX_REQUEST_SIZE:10MB}

  jackson:
    time-zone: ${JACKSON_TIMEZONE:Asia/Ho_Chi_Minh}
    deserialization:
      ACCEPT_SINGLE_VALUE_AS_ARRAY: ${JACKSON_ACCEPT_SINGLE_VALUE_AS_ARRAY:true}

server:
  port: ${PORT:8080}

logging:
  level:
    org.springframework.security: ${LOGGING_SECURITY_LEVEL:DEBUG}

jwt:
  base64-secret: ${JWT_BASE64_SECRET:TKeq+EY8YJvX3hDTlt6Wor8TxGyYDYSs5Nieew3VAzL0G9XQcNFFJNOmIv2isY2ol8F9d29wnbdD7azzM0oqFQ==}
  access-token-validity-in-seconds: ${JWT_ACCESS_TOKEN_VALIDITY_IN_SECONDS:86400}
  refresh-token-validity-in-seconds: ${JWT_REFRESH_TOKEN_VALIDITY_IN_SECONDS:8640000}

password:
  time_password_change_days: ${TIME_PASSWORD_CHANGE_DAYS:30}
